name: Build and Push ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws_access_key_id: ${{ secrets. aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1

      - name: Login ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login \
          --username AWS \
          --password-stdin 892706795696.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Image
        run: |
          docker build -t operator-services-images .

      - name: Tag Image
        run: |
          docker tag operator-services-images:latest \
          892706795696.dkr.ecr.us-east-1.amazonaws.com/operator-services-images:latest

      - name: Push Image
        run: |
          docker push \
          892706795696.dkr.ecr.us-east-1.amazonaws.com/operator-services-images:latest
